### ISSUE TITLE
Add server application to support printing over network

### ISSUE THREAD

**Issue by axlan** [K40Nano/K40Tools#4]
This is a feature I was planning on implementing for myself. Basically something that would let me leave a laptop plugged into the K40, but let me print from any computer on my network. Originally I was going to start from a fork of the base K40-Whisperer codebase, but this repo seems like a more natural fit if you are up taking pull requests.

I wasn't planning on anything too fully featured, I was thinking of doing a [remi](https://github.com/dddomodossola/remi) base GUI  that just supports uploading files and starting the cut, probably base on your CLI application.

**Comment by tatarize** [comment]
This repo should be the much more natural fit for it. I took the Whisperer code, fixed a number of bugs, and tore it down to the brass tacks, which was kind of needed as the Whisperer codebase is too coupled. It was basically to permit projects like yours without needing to do this same work or leaving it too tangled with various other elements.

**Comment by tatarize** [comment]
I have no problems adding such a project to the K40Nano group, or putting these example tools up on Pypi. Or just having you include them directly, they are MIT licensed rather than GPL (the main API is derived from Whisperer and thus GPL) but these are just example scripts just require the api code.

Putting them in Tools here, is somewhat inappropriate as these are intended to be example scripts for how you could use the API as it is built.

**Comment by tatarize** [comment]
What you are proposing seems like a exceptionally awesome program, even within the ambiguity.  It's either, or both, a webinterface for the K40, so you can control the K40 from an internal webpage with all the typical bells and whistles that requires basically building a sort of K40-Whisperer as an HTML application akin to some of the awesome software you find for 3d printers. 

Or, have the K40 work like a network print driver. There are some laser engravers that somewhat properly work like this. Printers have a couple different modes namely they work in both raster and vector modes and some engravers just let you use print from whatever to create an engraving. If the designs are raster it does that as a raster and if vector, it will do the vector part of the engraving. I believe Epilog Laser has something like this. Though I've not done much in the way of due diligence on that front. 

I can't quite tell from your post which you mean. But, I somewhat assume it's the former and by print you mean upload a relevant file and have it execute on the machine.

**Comment by tatarize** [comment]
Hm. Looking at the requirements for remi and the ease of doing such a thing I could very much see a basic version of this being fine for tools. Especially a web interface with a couple buttons to move the head. But, your idea seems pretty on the mark and could easily be fleshed out to well beyond any example scripts.

But, if the script is simple enough, it would be perfectly reasonable here. Just seems like it would be too easy to make a GUI as good or better than whisperer's in pretty short order with that stuff. And such a thing would likely warrant its own project.

**Comment by tatarize** [comment]
Loads up a web interface, accepts a press of the Home button to home the machine, then when you close that web-window it shuts down. Obviously the exit code is unneeded. But, there's no issues making a pretty advanced gui with that stuff, or a basic one. I daresay your project has a lot of merit.


```
import remi.gui as gui
from k40nano import NanoPlotter
from remi import start, App

class MyApp(App):
    def get_plotter(self):
        if self.plotter is None:
            self.plotter = NanoPlotter()
            self.plotter.open()
        return self.plotter

    def __init__(self, *args):
        super(MyApp, self).__init__(*args)
        self.plotter = NanoPlotter()
        self.plotter.open()

    def main(self):
        container = gui.VBox(width=120, height=100)
        self.lbl = gui.Label('Home Device')
        self.bt = gui.Button('Home')

        # setting the listener for the onclick event of the button
        self.bt.onclick.connect(self.on_button_pressed)

        # appending a widget to another, the first argument is a string key
        container.append(self.lbl)
        container.append(self.bt)


        tag = gui.Tag(_type='script')
        tag.add_child("javascript", """window.onunload=function(e){sendCallback('%s','%s');return "close?";};""" % (
        str(id(self)), "on_window_close"))
        container.add_child("onunloadevent", tag)

        # returning the root widget
        return container

    def on_window_close(self):
        #here you can handle the unload
        print("app closing")
        self.close()
        self.plotter.close()

    # listener function
    def on_button_pressed(self, widget):
        self.plotter.home()

# starts the web server
start(MyApp)
```

If you need something from me go ahead and ask. 

I've planned on adding an svg parser, even though such a thing would require giving the various colors different speeds and I had no place to put that information, or those options. 

The PNG parser seems to bug out if the filetype is weird, I tended to just convert them with imagemagic to PNG8 (rather than using something like PIL as Whisperer does). 

Though the most essential would seem to be the ability to get visual feedback from the GUI as to what the engraving should look like, though I have an exporter to png that could likely be shanghaied into that.

**Comment by axlan** [comment]
Thanks for the thoughtful reply. It was certainly a lot easier to use this as a basis for the project then my initial forays into disentangling the GUI elements from K40-Whisperer. I got a minimum viable project up and working, and I think I'll set up a new repo to keep things simple.

**Comment by axlan** [comment]
Created https://github.com/axlan/K40WebServer

**Comment by tatarize** [comment]
![remi_controller](https://user-images.githubusercontent.com/3302478/55131531-342e7d80-50dc-11e9-99f3-10b52760f229.png)
